---

# Installing utils
- name: installing task
  tags: installing
  block:
    - name: installing xfsdump
      yum:
        name: "{{ item }}"
        state: "present"
      loop:
        - xfsdump
        - vim
